directories:
  output: release
  buildResources: build
appId: com.docconverter.app
productName: Document Converter
files:
  - filter:
      - dist/**/*
      - node_modules/**/*
      - assets/**/*
extraResources:
  - from: assets/
    to: assets/
    filter:
      - '**/*'
  - from: scripts/
    to: scripts/
    filter:
      - setup-ollama-mac.js
      - setup-dependencies-mac.js
buildDependenciesFromSource: true
mac:
  category: public.app-category.productivity
  icon: assets/icon.svg
  target:
    - target: dmg
      arch:
        - x64
        - arm64
    - target: zip
      arch:
        - x64
        - arm64
  darkModeSupport: true
  hardenedRuntime: true
  gatekeeperAssess: false
  entitlements: assets/entitlements.mac.plist
  entitlementsInherit: assets/entitlements.mac.plist
  notarize:
    teamId: APPLE_TEAM_ID
win:
  icon: assets/icon.svg
  target:
    - target: nsis
      arch:
        - x64
        - ia32
    - target: portable
      arch:
        - x64
linux:
  icon: assets/icon.svg
  category: Office
  target:
    - target: AppImage
      arch:
        - x64
    - target: deb
      arch:
        - x64
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
publish:
  provider: github
  owner: turkishdeepkebab
  repo: Docdataapp
generateUpdatesFilesForAllChannels: true
dmg:
  title: DocDataApp
  icon: assets/icon.svg
  background: assets/dmg-background.png
  contents:
    - x: 140
      'y': 200
      type: file
    - x: 500
      'y': 200
      type: link
      path: /Applications
  window:
    width: 640
    height: 400
electronVersion: 27.3.11
