name: Release Automation

# Bu workflow manuel olarak tetiklenir veya belirli koşullarda çalışır
on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'Release type'
        required: true
        default: 'patch'
        type: choice
        options:
        - patch
        - minor
        - major
        - prerelease
      prerelease_type:
        description: 'Prerelease type (if prerelease is selected)'
        required: false
        default: 'beta'
        type: choice
        options:
        - alpha
        - beta
        - rc
  push:
    branches:
      - main
      - develop
    paths:
      - 'package.json'
      - 'CHANGELOG.md'

jobs:
  # Release version belirleme
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      is-prerelease: ${{ steps.version.outputs.is-prerelease }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Determine version
      id: version
      run: |
        if [ "${{ github.event_name }}" = "workflow_dispatch" ]; then
          RELEASE_TYPE="${{ github.event.inputs.release_type }}"
          PRERELEASE_TYPE="${{ github.event.inputs.prerelease_type }}"
        else
          # Otomatik version belirleme
          RELEASE_TYPE="patch"
          PRERELEASE_TYPE="beta"
        fi
        
        CURRENT_VERSION=$(node -p "require('./package.json').version")
        echo "Current version: $CURRENT_VERSION"
        
        if [ "$RELEASE_TYPE" = "prerelease" ]; then
          NEW_VERSION=$(npm version $PRERELEASE_TYPE --preid=$PRERELEASE_TYPE --no-git-tag-version --dry-run | sed 's/v//')
          echo "is-prerelease=true" >> $GITHUB_OUTPUT
        else
          NEW_VERSION=$(npm version $RELEASE_TYPE --no-git-tag-version --dry-run | sed 's/v//')
          echo "is-prerelease=false" >> $GITHUB_OUTPUT
        fi
        
        echo "New version: $NEW_VERSION"
        echo "version=$NEW_VERSION" >> $GITHUB_OUTPUT

  # Changelog oluşturma
  generate-changelog:
    needs: determine-version
    runs-on: ubuntu-latest
    outputs:
      changelog: ${{ steps.changelog.outputs.changelog }}
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Generate changelog
      id: changelog
      run: |
        # Son tag'i bul
        LAST_TAG=$(git describe --tags --abbrev=0 2>/dev/null || echo "")
        
        if [ -z "$LAST_TAG" ]; then
          # İlk release
          CHANGELOG="## 🎉 İlk Release v${{ needs.determine-version.outputs.version }}
          
          ### ✨ Yeni Özellikler
          - DocDataApp'in ilk sürümü
          - AI destekli doküman işleme
          - Çoklu platform desteği (Windows, macOS, Linux)
          - Modern ve kullanıcı dostu arayüz
          
          ### 🚀 Kurulum
          İşletim sisteminize uygun installer'ı indirin ve kurun."
        else
          # Son tag'den bu yana değişiklikleri al
          CHANGELOG=$(git log $LAST_TAG..HEAD --pretty=format:"- %s" --no-merges)
          
          if [ -z "$CHANGELOG" ]; then
            CHANGELOG="## 🔧 v${{ needs.determine-version.outputs.version }}
            
            ### 🐛 Bug Fixes
            - Çeşitli hata düzeltmeleri ve iyileştirmeler"
          else
            CHANGELOG="## 🚀 v${{ needs.determine-version.outputs.version }}
            
            ### 📝 Değişiklikler
            $CHANGELOG"
          fi
        fi
        
        # Changelog'u dosyaya yaz
        echo "$CHANGELOG" > CHANGELOG.md
        
        # Output olarak set et
        echo "changelog<<EOF" >> $GITHUB_OUTPUT
        echo "$CHANGELOG" >> $GITHUB_OUTPUT
        echo "EOF" >> $GITHUB_OUTPUT

  # Version güncelleme ve tag oluşturma
  create-release:
    needs: [determine-version, generate-changelog]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}
        token: ${{ secrets.GITHUB_TOKEN }}
        
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Configure Git
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git config --local user.password ${{ secrets.GITHUB_TOKEN }}
        
    - name: Update version
      run: |
        if [ "${{ needs.determine-version.outputs.is-prerelease }}" = "true" ]; then
          npm version prerelease --preid=beta --no-git-tag-version
        else
          npm version ${{ github.event.inputs.release_type || 'patch' }} --no-git-tag-version
        fi
        
    - name: Create tag
      run: |
        VERSION=$(node -p "require('./package.json').version")
        git add package.json CHANGELOG.md
        git commit -m "chore: bump version to v$VERSION"
        git tag "v$VERSION"
        git push origin main
        git push origin "v$VERSION"
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  # Build ve release (build.yml workflow'unu tetikler)
  trigger-build:
    needs: create-release
    runs-on: ubuntu-latest
    steps:
    - name: Trigger build workflow
      uses: actions/github-script@v7
      with:
        script: |
          const { owner, repo } = context.repo;
          const version = '${{ needs.determine-version.outputs.version }}';
          
          // Build workflow'unu tetikle
          await github.rest.actions.createWorkflowDispatch({
            owner,
            repo,
            workflow_id: 'build.yml',
            ref: 'main'
          });
          
          console.log(`Build workflow triggered for version v${version}`);
