name: Test Workflow

on:
  workflow_dispatch:  # Sadece manuel tetikleme
  # push:
  #   tags:
  #     - 'v*'

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Test step
        run: |
          echo "✅ Test workflow is working!"
          echo "Tag: ${{ github.ref_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Event: ${{ github.event_name }}"
